### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by ecic2002** [s4wny/rainmeter-headphones-speaker-switcher#1]
When clicking a button I receive the error; The program can't start because MSVCP120D.dll is missing from you computer. Help Please!

**Comment by s4wny** [comment]
The problem is that you don't have the Visual C++ Redistributable Packages. You can download it from microsofts website: http://www.microsoft.com/en-US/download/details.aspx?id=40784

**Comment by s4wny** [comment]
Edit: Sorry, wasn't a problem with your computer. I had included the wrong .exe file (the debug .exe and not the release .exe). The problem is now fixed!
